export default {
    name:"product",
    title:"Product",
    type:"document",
    fields:[
        {
            name:"id",
            title:"Id",
            type:"string"
        },
        {
            name:"name",
            title:"Name",
            type:"string"
        },
        {
            name:"title",
            title:"Title",
            type:"string"
        },
        {
            name:"category",
            title:"Category",
            type:"string"
        },
        {
            name:"price",
            title:"Price",
            type:"number"
        },
        {
            name:"image",
            title:"Image",
            type:"image"
        },
    ]
}